"""Obsidian Markdown Vault synchronization, highlights serialization, and frontmatter management."""
from __future__ import annotations

import json
import re
from datetime import datetime
from pathlib import Path
from typing import Optional, List
import frontmatter

from app.config import VAULT_DIR, LINKS_VAULT_DIR, BRIEFINGS_VAULT_DIR
from app.models import Link, LinkStatus, LinkType, Highlight


def slugify(text: str) -> str:
    """Create a URL/filename-safe slug."""
    text = text.lower().strip()
    text = re.sub(r'[^\w\s-]', '', text)
    text = re.sub(r'[-\s]+', '-', text)
    return text[:60].strip("-") or "link"


def link_to_vault_file(link: Link) -> Path:
    """Determine the relative vault file path for a link."""
    date_prefix = link.created_at[:10]
    slug = slugify(link.title or link.domain or "item")
    filename = f"{date_prefix}-{slug}.md"
    return LINKS_VAULT_DIR / filename


def save_link_to_vault(link: Link) -> Path:
    """Save a Link model as an individual Obsidian markdown note with YAML frontmatter."""
    LINKS_VAULT_DIR.mkdir(parents=True, exist_ok=True)
    file_path = link_to_vault_file(link)

    metadata = {
        "id": link.id,
        "title": link.title,
        "url": link.url,
        "entry_type": link.entry_type.value,
        "tags": link.tags,
        "status": link.status.value,
        "added": link.created_at[:10],
        "author": link.author or "",
        "site_name": link.site_name or "",
        "domain": link.domain or "",
        "reading_time_minutes": link.reading_time_minutes,
        "word_count": link.word_count,
        "cover_image": link.cover_image or "",
        "favicon": link.favicon or "",
        "offline_snapshot": link.offline_snapshot_path or "",
        "highlights": [h.model_dump() for h in link.highlights],
        "media_meta": link.media_meta,
    }

    # Markdown body
    body_sections = [
        f"# {link.title}\n",
        f"> **URL**: [{link.url}]({link.url})  ",
        f"> **Type**: `{link.entry_type.value}` | **Tags**: {' '.join('#' + t for t in link.tags)} | **Status**: `{link.status.value}`\n",
        "## Summary",
        link.summary or "*(No summary available)*\n",
    ]

    # Media details (GitHub, ArXiv, YouTube)
    if link.media_meta:
        media_parts = []
        if "github" in link.media_meta:
            gh = link.media_meta["github"]
            media_parts.append(
                f"- **GitHub**: ⭐ {gh.get('stars', 0):,} stars | 🍴 {gh.get('forks', 0):,} forks | "
                f"Language: `{gh.get('language') or 'N/A'}` | License: `{gh.get('license') or 'None'}`"
            )
        if "arxiv_id" in link.media_meta:
            media_parts.append(f"- **ArXiv PDF**: [{link.media_meta.get('pdf_url')}]({link.media_meta.get('pdf_url')})")
            if link.media_meta.get("bibtex"):
                media_parts.append(f"```bibtex\n{link.media_meta['bibtex']}\n```")
        if "youtube_id" in link.media_meta:
            yt_id = link.media_meta["youtube_id"]
            media_parts.append(f"- **YouTube Video**: [Watch on YouTube](https://www.youtube.com/watch?v={yt_id})")

        if media_parts:
            body_sections.extend([
                "## Resource Details",
                "\n".join(media_parts),
                "",
            ])

    # User Notes
    if link.user_notes:
        body_sections.extend([
            "## Personal Notes",
            link.user_notes.strip(),
            "",
        ])

    # Highlights & Quotes
    if link.highlights:
        hl_lines = []
        for hl in link.highlights:
            hl_lines.append(f"> \"{hl.text}\"")
            if hl.note:
                hl_lines.append(f"> — *Note: {hl.note}* ({hl.created_at[:10]})")
            else:
                hl_lines.append(f"> — *({hl.created_at[:10]})*")
            hl_lines.append("")
        body_sections.extend([
            "## Highlights & Quotes",
            "\n".join(hl_lines),
        ])

    # Archived Content Body
    if link.content_markdown and link.content_markdown.strip():
        body_sections.extend([
            "## Archived Content",
            link.content_markdown.strip(),
            "",
        ])

    post = frontmatter.Post("\n".join(body_sections), **metadata)
    file_path.write_text(frontmatter.dumps(post), encoding="utf-8")

    # Keep master INDEX.md updated
    update_master_index()
    return file_path


def update_master_index():
    """Regenerate master INDEX.md with links to all vault notes."""
    index_file = VAULT_DIR / "INDEX.md"
    files = sorted(LINKS_VAULT_DIR.glob("*.md"), reverse=True)

    lines = [
        "# Link Vault Index",
        "",
        "> Master index auto-generated by Hermes Librarian.",
        "",
        "| Date | Title | Type | Tags | Status | Highlights |",
        "| :--- | :--- | :--- | :--- | :--- | :--- |",
    ]

    for f in files:
        try:
            post = frontmatter.load(f)
            title = post.metadata.get("title", f.stem)
            entry_type = post.metadata.get("entry_type", "article")
            tags = " ".join("#" + t for t in post.metadata.get("tags", []))
            status = post.metadata.get("status", "inbox")
            added = post.metadata.get("added", f.name[:10])
            hls = len(post.metadata.get("highlights", []))
            rel_link = f"links/{f.name}"

            title_escaped = title.replace("|", "\\|")
            hl_str = f"🖍️ {hls}" if hls > 0 else "-"
            lines.append(f"| {added} | [{title_escaped}]({rel_link}) | `{entry_type}` | {tags} | `{status}` | {hl_str} |")
        except Exception:
            continue

    lines.append("")
    index_file.write_text("\n".join(lines), encoding="utf-8")


def import_vault_to_database() -> int:
    """Parse all markdown files in the vault and sync to the SQLite database."""
    from app.database import save_link
    import uuid

    if not LINKS_VAULT_DIR.exists():
        return 0

    count = 0
    for file_path in sorted(LINKS_VAULT_DIR.glob("*.md")):
        try:
            post = frontmatter.load(file_path)
            meta = post.metadata

            url = meta.get("url")
            if not url:
                continue

            link_id = meta.get("id") or str(uuid.uuid4())[:8]
            title = meta.get("title") or file_path.stem
            added = meta.get("added") or file_path.name[:10]
            created_at = f"{added} 12:00:00"

            tags = meta.get("tags", [])
            if isinstance(tags, str):
                tags = [t.strip().lstrip("#") for t in tags.split() if t.strip()]

            # Parse highlights
            raw_hls = meta.get("highlights", [])
            highlights = [Highlight(**h) if isinstance(h, dict) else h for h in raw_hls]

            # Extract sections from body
            content = post.content
            summary = meta.get("summary")
            notes = meta.get("user_notes")
            archive_content = ""

            if "## Archived Content" in content:
                parts = content.split("## Archived Content")
                archive_content = parts[1].strip()

            if not summary and "## Summary" in content:
                summary_part = content.split("## Summary")[1]
                if "## " in summary_part:
                    summary_part = summary_part.split("## ")[0]
                summary = summary_part.strip()

            link = Link(
                id=link_id,
                url=url,
                title=title,
                author=meta.get("author"),
                site_name=meta.get("site_name"),
                domain=meta.get("domain"),
                entry_type=LinkType(meta.get("entry_type", "article")),
                tags=tags,
                status=LinkStatus(meta.get("status", "inbox")),
                summary=summary or "",
                user_notes=notes,
                content_markdown=archive_content,
                cover_image=meta.get("cover_image"),
                favicon=meta.get("favicon"),
                reading_time_minutes=int(meta.get("reading_time_minutes", 1)),
                word_count=int(meta.get("word_count", len(archive_content.split()))),
                created_at=created_at,
                updated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                vault_file=f"links/{file_path.name}",
                media_meta=meta.get("media_meta", {}),
                highlights=highlights,
                offline_snapshot_path=meta.get("offline_snapshot"),
            )
            save_link(link)
            count += 1
        except Exception as e:
            print(f"Error syncing {file_path.name}: {e}")

    return count


def create_vault_briefing(days: int = 7, title: Optional[str] = None, custom_notes: Optional[str] = None) -> Path:
    """Generate an Obsidian research briefing note in data/vault/briefings/ with wikilinks."""
    from datetime import datetime, timedelta
    from app.database import get_links_since

    BRIEFINGS_VAULT_DIR.mkdir(parents=True, exist_ok=True)

    since_date = datetime.now() - timedelta(days=days)
    since_str = since_date.strftime("%Y-%m-%d %H:%M:%S")
    links = get_links_since(since_str)

    date_today = datetime.now().strftime("%Y-%m-%d")
    year_week = datetime.now().strftime("%Y-W%U")
    filename = f"{date_today}-briefing-{year_week}.md"
    file_path = BRIEFINGS_VAULT_DIR / filename

    total = len(links)
    by_status: dict[str, int] = {}
    by_type: dict[str, int] = {}
    all_tags: list[str] = []

    for l in links:
        by_status[l.status.value] = by_status.get(l.status.value, 0) + 1
        by_type[l.entry_type.value] = by_type.get(l.entry_type.value, 0) + 1
        all_tags.extend(l.tags)

    tag_counts: dict[str, int] = {}
    for t in all_tags:
        tag_counts[t] = tag_counts.get(t, 0) + 1
    top_tags = sorted(tag_counts.items(), key=lambda x: x[1], reverse=True)[:8]

    metadata = {
        "title": title or f"Research Briefing ({date_today})",
        "type": "briefing",
        "period_days": days,
        "date": date_today,
        "week": year_week,
        "items_count": total,
        "tags": [t[0] for t in top_tags],
    }

    lines = [
        f"# {metadata['title']}\n",
        f"> **Period**: Past {days} days ({since_date.strftime('%Y-%m-%d')} to {date_today})  ",
        f"> **Archived Items**: {total} | **Tags**: {' '.join('#' + t[0] for t in top_tags) if top_tags else 'None'}\n",
        "## Executive Summary\n",
    ]

    if custom_notes:
        lines.append(f"{custom_notes.strip()}\n")
    else:
        type_str = ", ".join(f"{k}: {v}" for k, v in by_type.items()) if by_type else "no items"
        lines.append(f"Weekly reading and research digest compiled by Hermes Agent. During this period, **{total}** items were captured into the knowledge vault across `{type_str}`.\n")

    lines.append("## Reading Pipeline\n")
    lines.append(f"- **Inbox**: {by_status.get('inbox', 0)}")
    lines.append(f"- **Currently Reading**: {by_status.get('reading', 0)}")
    lines.append(f"- **Archived / Completed**: {by_status.get('archived', 0)}")
    lines.append(f"- **Favorites**: {by_status.get('favorite', 0)}\n")

    lines.append("## Captured Resources\n")
    if not links:
        lines.append("*(No links archived during this period)*\n")
    else:
        for l in links:
            target_slug = Path(l.vault_file).stem if l.vault_file else slugify(l.title or "link")
            wikilink = f"[[{target_slug}|{l.title}]]"
            tags_str = " ".join(f"#{t}" for t in l.tags)
            status_icon = "⭐" if l.status.value == "favorite" else ("📖" if l.status.value == "reading" else "📥")

            lines.append(f"### {status_icon} {wikilink}")
            lines.append(f"- **Source**: [{l.domain or l.url}]({l.url}) | **Type**: `{l.entry_type.value}` | **Tags**: {tags_str or 'None'}")
            if l.summary:
                summary_excerpt = l.summary.strip().replace("\n", " ")
                if len(summary_excerpt) > 280:
                    summary_excerpt = summary_excerpt[:277] + "..."
                lines.append(f"- **Summary**: {summary_excerpt}")
            if l.highlights:
                lines.append(f"- **Highlights**: {len(l.highlights)} saved quote(s)")
            if l.user_notes:
                lines.append(f"- **Personal Note**: *{l.user_notes.strip()}*")
            lines.append("")

    post = frontmatter.Post("\n".join(lines), **metadata)
    file_path.write_text(frontmatter.dumps(post), encoding="utf-8")
    return file_path
